### PR TITLE
Add GitHub issue template

### PR DESCRIPTION
**Pull request by xiongtx**
This will improve the quality of bug reports/feature requests.

### CODE REVIEW

**Comment by cpitclaudel** [comment]
Thanks! But I'm not sure I want to force people to use this template, or even recommend it. I'd much rather treat issues as a space for discussion -- most issues up to this point are not bugs that I'd need to reproduce, but rather feature requests or comments.  In those cases version information and descriptions of actual/expected behaviors feel artificial.

**Comment by xiongtx** [comment]
:man_shrugging: Up to you. I find that such templates are valuable for prompting users to provide necessary information and preventing wasteful follow-up questions like "What OS are you using?".

**Comment by cpitclaudel** [comment]
Makes sense. In the context of Emacs Lisp, I haven't had to ask for OS information often, but your point is well taken. Do you want to open a PR for a shorter message, asking for platform and Emacs version, and suggesting to add a backtrace when reporting a bug?

**Comment by xiongtx** [comment]
Not sure what shorter message you're looking for. Anyways, you get the idea--you can add an issue template if you want, or not.

**Pull request closed without merging**
