### PR TITLE
Refactor to make it easier to append to the contents of an overlay

### PR DESCRIPTION
**Pull request by fmdkdd**
As outlined in stardiviner/flycheck-inline#4.

Here is the client code I'm using on flycheck-inline's side:
```emacs-lisp
(setq flycheck-inline-display-function
      (lambda (msg pos)
        (let* ((ov (save-excursion
                     (goto-char pos)
                     (quick-peek--overlay-ensure-at (point))))
               (contents (overlay-get ov 'raw-msg)))
          (overlay-put ov 'raw-msg
                       (concat contents
                               (when contents "\n")
                               msg))
          (quick-peek--update ov 0 'none)))
      flycheck-inline-clear-function #'quick-peek-hide)
```
Two things:
1. Should we make a proper API in `quick-peek` to get and set the raw string, or is updating the overlay property enough?  Even better for me would be to have a `quick-peek-update-content (ov str)` that does this behind the scenes.
2. I think we should either remove the argument to `-overlay-ensure-at` (and rename it `-overlay-ensure-at-point`, or move the `save-excursion` into it.  Currently, passing a position other than point won't work if the overlay has to be created.

### CODE REVIEW

**Comment by cpitclaudel** [comment]
Excellent, thanks. Will merge tonight.

**Comment by fmdkdd** [comment]
@cpitclaudel Friendly ping.

**Comment by cpitclaudel** [comment]
Thanks for the ping. I pushed two further refactorings on top of your commit to address the two issues you mentioned.  I also moved more functions into the public API. `quick-peek-overlay-ensure-at` should allow you to create a quick-peek overlay, whose string you can then set with `setf` on `quick-peek-overlay-contents`.  After adding all the strings, you can call `quick-peek-overlay-update` on each of the overlays.

I put everything on https://github.com/cpitclaudel/quick-peek/tree/fmdkdd-refactor-for-flycheck-inline . Can you give it a try?

**Comment by fmdkdd** [comment]
That works nicely!  Here is what I'm using now:

```emacs-lisp
(setq flycheck-inline-display-function
      (lambda (msg pos)
        (let* ((ov (quick-peek-overlay-ensure-at pos))
               (contents (quick-peek-overlay-contents ov)))
          (setf (quick-peek-overlay-contents ov)
                (concat contents (when contents "\n") msg))
          (quick-peek-update ov)))
      flycheck-inline-clear-function #'quick-peek-hide)
```

I think it's as nice as it can be.  You can merge that branch and close this PR :+1:

**Comment by cpitclaudel** [comment]
Great, thanks for testing!

**Comment by cpitclaudel** [comment]
Oh, btw; I think you could do a single call to `quick-peek-update`, instead of calling it repeatedly.

**Comment by fmdkdd** [comment]
> Oh, btw; I think you could do a single call to quick-peek-update, instead of calling it repeatedly.

I know, but the API on my side does not let me do that simply.  I either have to collect all messages for the current position, or I have to add a `flycheck-inline-finish-display` function.

Were I to integrate `quick-peek` completely in `flycheck-inline`, then yes, that would be easy to do.  If performance becomes an issue, then sure I'll reconsider.

**Comment by cpitclaudel** [comment]
Oh, I see.  Makes sense :)

**Pull request merged**
