### PR TITLE
Avoid background face

### PR DESCRIPTION
**Pull request by xiongtx**
Add customizable variable to control whether `quick-peek-background-face` is used.

### CODE REVIEW

**Comment by cpitclaudel** [comment]
Thanks. Can you clarify why it's not enough to be able to set the face's properties to `undefined` instead? This setting looks redundant, but it may be because I'm not sure what you're trying to achieve :/ if you intend to let-bind this variable then it shouldn't be a defcustom, right?

**Comment by xiongtx** [comment]
You're right that the proper use of such a variable should be as a `let`-bound var, not a `defcustom`. This has been fixed.

**Comment by cpitclaudel** [comment]
Thanks. The problem is clear, and this fix makes sense. I'm not thrilled about this particular solution, though. Can we find a way to apply the background face in addition to existing faces?

IIUC the issue is that `font-lock-face` is an alias for `face`, and thus when quick-peek adds its background face it takes precedence over font-lock-face. Can you think of a way to add the background face to all text?

This way we'd respect quick-peek-background-face and still display faces properly.  I imagine it might require defining a variant of `font-lock-append-text-property`.  I'm happy to take care of that, if you want.

**Comment by xiongtx** [comment]
> Can you think of a way to add the background face to all text?

Why? Suppose I wanted documentation popup for `foo-lookup` to have a face that isn't `quick-peek-background-face` and `bar-lookup` to use `quick-peek-background-face`. This *should* be controlled at the level of the call to `quick-peek-show`, IMO.

**Comment by cpitclaudel** [comment]
Can't you add your own background to foo-lookup?

**Comment by xiongtx** [comment]
What do you mean? I'm rather lost.

Here's a summary of the current situation:

1. Caller of `quick-peek-show` [does not necessarily control](https://github.com/cpitclaudel/quick-peek/issues/4#issuecomment-301669727) fontification of input text
2. `quick-peek-background-face` would override text propertized with `font-lock-face`

Therefore, if the input text has `font-lock-face`, there is **no value** `quick-peek-background-face` can be set to (even all `undefined`) that does not override the input text.

Changing the way text properties override each other seems like an Emacs-level problem, not something to be solved in this package.

**Comment by cpitclaudel** [comment]
I mean replacing the definition of `--prepare-for-definition-overlay` by the following:

```

(defun quick-peek--append-face (start end face)
  "Append face FACE to START .. END.
This respects `font-lock-doc-face', unlike `font-lock-append-text-property'."
  (setq face (if (listp face) face (list face)))
  (while (/= start end)
    (let* ((next (min (next-single-property-change start 'face nil end)
                      (next-single-property-change start 'font-lock-face nil end)))
           (prop 'face)
           (prev-face (get-text-property start 'face)))
      (unless prev-face
        (when (setq prev-face (get-text-property start 'font-lock-face))
          (setq prop 'font-lock-face)))
      (setq prev-face (if (listp prev-face) prev-face (list prev-face)))
      (put-text-property start next prop (append prev-face face))
      (setq start next))))

(defun quick-peek--prepare-for-definition-overlay (str offset &optional max-lines)
  "Prepare STR for display in a quick peek window.
Return value is a string that includes properties surrounding it
with two thin horizontal lines, indented by OFFSET, and truncated
to show at most MAX-LINES.  If text doesn't fit horizontally
between OFFSET and the end of the window, it will be moved left."
  (with-temp-buffer
    (insert str "\n")
    (when max-lines
      (quick-peek--truncate-buffer (point-min) max-lines " …"))
    (let* ((text-width (+ (quick-peek--max-line-length) 5)) ;; +5 for wide characters
           (max-offset (- (window-body-width) text-width))
           (real-offset (max 0 (min offset max-offset))))
      (quick-peek--prefix-all-lines (make-string real-offset ?\s)))
    (quick-peek--append-face (point-min) (point-max) 'quick-peek-background-face)
    (quick-peek--insert-spacer (point-min) "\n" "\n")
    (quick-peek--insert-spacer (point-max) "\n" "\n")
    (buffer-string)))
```

This fixes the example you posted. Are there other issues that it doesn't fix? If not, I see that as a preferable solution.  It ensures that the background face is always applied *in addition* to already specified faces.

Sorry I didn't describe it clearly previously. Hopefully a concrete implementation speaks clearly.

**Comment by xiongtx** [comment]
Ah, I think I got it--at least, as far as `font-lock-face` is concerned.

`font-lock-face` *should* take priority over `face`, but only if `font-lock-mode` is active. In `quick-peek--prepare-for-definition-overlay`, a temp buffer is created, but `font-lock-mode` is not active. Therefore, the text in the temp buffer is not propertized.

Adding:

```emacs-lisp
(with-temp-buffer
  (font-lock-mode 1)
  ...
  (font-lock-ensure)
  (buffer-string))
```

fixes it.

*However*, I still think that whether to apply `quick-peek-background-face` to input text is a *per-instance* concern. 

If input text is propertized with `face` instead of `font-lock-face`, `quick-peek-background-face` will override it unless it's set to `undefined` for all attributes. It's possible that in some calls to `quick-peek-show`, the user *wants* `quick-peek-background-face`, while in others they don't.

**Comment by xiongtx** [comment]
Ah, I think I got it--at least, as far as `font-lock-face` is concerned.

`font-lock-face` *should* take priority over `face`, but only if `font-lock-mode` is active. In `quick-peek--prepare-for-definition-overlay`, a temp buffer is created, but `font-lock-mode` is not activated. Therefore, the text in the temp buffer is not propertized.

Adding:

```emacs-lisp
(with-temp-buffer
  (font-lock-mode 1)
  ...
  (font-lock-ensure)
  (buffer-string))
```

fixes it.

*However*, I still think that whether to apply `quick-peek-background-face` to input text is a *per-instance* concern. 

If input text is propertized with `face` instead of `font-lock-face`, `quick-peek-background-face` will override it unless it's set to `undefined` for all attributes. It's possible that in some calls to `quick-peek-show`, the user *wants* `quick-peek-background-face`, while in others they don't.

**Comment by cpitclaudel** [comment]
> If input text is propertized with face instead of font-lock-face, quick-peek-background-face will override it unless it's set to undefined for all attributes. It's possible that in some calls to quick-peek-show, the user wants quick-peek-background-face, while in others they don't.

The patch that I posted above was supposed to address this. Can you try it and see if it works for you?

**Comment by xiongtx** [comment]
Updated with your changes.

**Comment by xiongtx** [comment]
Ping @cpitclaudel

**Comment by xiongtx** [comment]
2x ping @cpitclaudel

**Comment by xiongtx** [comment]
@cpitclaudel Any chance we can wrap this up? Either your suggestion or mine is fine. If we wait any longer I'll have completely forgotten what the solutions are :smile:.

**Comment by cpitclaudel** [comment]
It turns out that there was a much simpler solution all along. Pushed :)

**Pull request closed without merging**
